import re


def clean_extracted_text(text: str) -> str:
    if not text:
        return ""

    # Remove non-printable control characters generated by OCR/PDF parsers.
    text = re.sub(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]", "", text)

    # Normalize line endings to Unix style for consistency.
    text = text.replace("\r\n", "\n").replace("\r", "\n")

    # Split the document into individual lines for processing.
    lines = text.split("\n")

    # Store cleaned lines and track seen lines to avoid duplicates.
    cleaned_lines = []
    seen_lines = set()

    # Process each line to clean and filter out unwanted content.
    for line in lines:

        # Remove leading and trailing whitespace.
        line = line.strip()

        # Replace multiple spaces or tabs with a single space.
        line = re.sub(r"[ \t]+", " ", line)

        if not line:
            cleaned_lines.append("")
            continue

        # Remove very short OCR artifacts such as ".", "|", ":" or isolated numbers.
        if len(line) <= 2 and not line.isalpha():
            continue

        # Remove lines that consist only of symbols.
        # Examples:
        # ----------
        # ********
        # ________
        if re.fullmatch(r"[\W_]+", line):
            continue

        # Remove duplicate lines
        normalized_line = line.lower()
        if normalized_line in seen_lines:
            continue

        seen_lines.add(normalized_line)
        cleaned_lines.append(line)

    cleaned_text = "\n".join(cleaned_lines)

    # Collapse three or more consecutive blank lines into two.
    cleaned_text = re.sub(r"\n{3,}", "\n\n", cleaned_text)

    # Remove trailing whitespace from every line.
    cleaned_text = "\n".join(line.strip() for line in cleaned_text.split("\n"))

    return cleaned_text.strip()